services:
  webapp:
    build: .
    ports:
      - '80:80'
    environment:
      - REDIS=cache
      - REDIS_PWD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cache:
    driver: local